"""initial_schema

Revision ID: 681e8410935f
Revises: 
Create Date: 2026-06-10 14:28:10.756364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681e8410935f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_sets', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['locked_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_sets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
